// <auto-generated />
using System;
using Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AplicacionBdContexto))]
    [Migration("20251126203533_HacerCurpOpcionalEnAlumno")]
    partial class HacerCurpOpcionalEnAlumno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CintaActualId")
                        .HasColumnType("int");

                    b.Property<int?>("ClaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ConceptoMensualidadId")
                        .HasColumnType("int");

                    b.Property<string>("Curp")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTutor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Enfermedades")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TelefonoTutor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Alumnos_Activo");

                    b.HasIndex("CintaActualId")
                        .HasDatabaseName("IX_Alumnos_CintaActualId");

                    b.HasIndex("ClaseId")
                        .HasDatabaseName("IX_Alumnos_ClaseId");

                    b.HasIndex("ConceptoMensualidadId");

                    b.HasIndex("Curp")
                        .IsUnique()
                        .HasDatabaseName("IX_Alumnos_Curp")
                        .HasFilter("[Curp] IS NOT NULL");

                    b.HasIndex("EmailTutor")
                        .HasDatabaseName("IX_Alumnos_EmailTutor");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Alumnos_Slug");

                    b.HasIndex("Activo", "ClaseId")
                        .HasDatabaseName("IX_Alumnos_Activo_ClaseId");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.AlumnoInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ConceptoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ConceptoId");

                    b.ToTable("AlumnoInscripciones", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("UsuarioRegistroId");

                    b.HasIndex("AlumnoId", "ClaseId", "Fecha")
                        .IsUnique();

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Cinta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cintas", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoClase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Concepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoConcepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Conceptos", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int?>("AlumnoInscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("ConceptoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("IX_Pagos_AlumnoId");

                    b.HasIndex("AlumnoInscripcionId");

                    b.HasIndex("ConceptoId")
                        .HasDatabaseName("IX_Pagos_ConceptoId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pagos_Estado");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Pagos_Fecha");

                    b.HasIndex("UsuarioRegistroId");

                    b.HasIndex("AlumnoId", "Fecha")
                        .HasDatabaseName("IX_Pagos_AlumnoId_Fecha");

                    b.HasIndex("Estado", "Fecha")
                        .HasDatabaseName("IX_Pagos_Estado_Fecha");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Habilitado")
                        .HasDatabaseName("IX_Usuarios_Habilitado");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_NombreUsuario");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Slug");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Api.Entidades.Alumno", b =>
                {
                    b.HasOne("Api.Entidades.Cinta", "CintaActual")
                        .WithMany("Alumnos")
                        .HasForeignKey("CintaActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Entidades.Clase", "Clase")
                        .WithMany("Alumnos")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Entidades.Concepto", "ConceptoMensualidad")
                        .WithMany()
                        .HasForeignKey("ConceptoMensualidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CintaActual");

                    b.Navigation("Clase");

                    b.Navigation("ConceptoMensualidad");
                });

            modelBuilder.Entity("Api.Entidades.AlumnoInscripcion", b =>
                {
                    b.HasOne("Api.Entidades.Alumno", "Alumno")
                        .WithMany("AlumnoInscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entidades.Concepto", "Concepto")
                        .WithMany("AlumnoInscripciones")
                        .HasForeignKey("ConceptoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Concepto");
                });

            modelBuilder.Entity("Api.Entidades.Asistencia", b =>
                {
                    b.HasOne("Api.Entidades.Alumno", "Alumno")
                        .WithMany("Asistencias")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entidades.Clase", "Clase")
                        .WithMany("Asistencias")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Entidades.Usuario", "UsuarioRegistro")
                        .WithMany("AsistenciasRegistradas")
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Api.Entidades.Pago", b =>
                {
                    b.HasOne("Api.Entidades.Alumno", "Alumno")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Entidades.AlumnoInscripcion", "AlumnoInscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoInscripcionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Entidades.Concepto", "Concepto")
                        .WithMany("Pagos")
                        .HasForeignKey("ConceptoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Entidades.Usuario", "UsuarioRegistro")
                        .WithMany("PagosRegistrados")
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("AlumnoInscripcion");

                    b.Navigation("Concepto");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Api.Entidades.Alumno", b =>
                {
                    b.Navigation("AlumnoInscripciones");

                    b.Navigation("Asistencias");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Entidades.AlumnoInscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Entidades.Cinta", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("Api.Entidades.Clase", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Api.Entidades.Concepto", b =>
                {
                    b.Navigation("AlumnoInscripciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Api.Entidades.Usuario", b =>
                {
                    b.Navigation("AsistenciasRegistradas");

                    b.Navigation("PagosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
